apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-28T01:51:36Z"
  generation: 1
  labels:
    app: java-app
  name: java-app
  namespace: default
  resourceVersion: "6701"
  selfLink: /apis/apps/v1/namespaces/default/deployments/java-app
  uid: 5fa71eb4-499b-4541-8697-0e0d37b78dda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app
    spec:
      containers:
      - image: gcr.io/iamotis/java-app:v1
        imagePullPolicy: IfNotPresent
        name: java-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-28T01:51:38Z"
    lastUpdateTime: "2021-07-28T01:51:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-28T01:51:36Z"
    lastUpdateTime: "2021-07-28T01:51:38Z"
    message: ReplicaSet "java-app-6d7ff4b969" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
